service: tours-api

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    CLOUDINARY_CLOUD_NAME: ${env:CLOUDINARY_CLOUD_NAME}
    CLOUDINARY_API_KEY: ${env:CLOUDINARY_API_KEY}
    CLOUDINARY_API_SECRET: ${env:CLOUDINARY_API_SECRET}
    TOKEN_SECRET: ${env:TOKEN_SECRET}
    NODE_ENV: ${env:NODE_ENV}

functions:
  app:
    handler: src/lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
      - httpApi:
          path: /
          method: ANY
