name: Deploy Tours App

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy-user:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./user

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build
        env:
          API_URL: ${{ vars.API_URL }}
          MAPBOX_TOKEN: ${{ vars.MAPBOX_TOKEN }}

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::068514513330:role/go-tour-role
          aws-region: us-east-1

      - run: aws s3 sync ./dist s3://go-tour-user --delete

      - run: |
          aws cloudfront create-invalidation \
            --distribution-id EG0TGI924YJ7 \
            --paths "/*"



  deploy-admin:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./admin

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build
        env:
          API_URL: ${{ vars.API_URL }}
          MAPBOX_TOKEN: ${{ vars.MAPBOX_TOKEN }}

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::068514513330:role/go-tour-role
          aws-region: us-east-1

      - run: aws s3 sync ./dist s3://go-tour-admin --delete

      - run: |
          aws cloudfront create-invalidation \
            --distribution-id ES94Y42I2R8PL \
            --paths "/*"


  deploy-backend:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::068514513330:role/go-tour-role
          aws-region: us-east-1

      - name: Deploy with Serverless
        run: npx serverless deploy
        env:
          DATABASE_URL: ${{ vars.DATABASE_URL }}
          CLOUDINARY_CLOUD_NAME: ${{ vars.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ vars.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ vars.CLOUDINARY_API_SECRET }}
          TOKEN_SECRET: ${{ vars.TOKEN_SECRET }}
          NODE_ENV: production
